swagger: '2.0'
info:
  version: '1.0.0'
  title: Portal API
host: localhost:3000
basePath: /api/v1
schemes:
  # NOTE: remove http to make production-grade
  - http
  - https
consumes:
  - application/json
  - application/x-www-form-urlencoded
produces:
  - application/json
paths:
  '/patients/{patientName}/history':
    x-swagger-router-controller: patients
    get:
      description: Retrieve a patient history
      operationId: getHistory
      parameters:
        - $ref: '#/parameters/pathPatientName'
        - $ref: '#/parameters/queryRequester'
      responses:
        '200':
          description: Successful request
          schema:
            $ref: '#/definitions/Patient'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
        default:
          $ref: '#/responses/GeneralError'
  '/patients/{patientName}/enableDoctor':
    x-swagger-router-controller: patients
    put:
      description: Enable a Doctor
      operationId: enableDoctor
      parameters:
        - $ref: '#/parameters/pathPatientName'
        - $ref: '#/parameters/bodyDoctor'
      responses:
        '201':
          description: Successful request
          schema:
            $ref: '#/definitions/Patient'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
        default:
          $ref: '#/responses/GeneralError'
  '/patients/{patientName}/disableDoctor':
    x-swagger-router-controller: patients
    put:
      description: Disable a Doctor
      operationId: disableDoctor
      parameters:
        - $ref: '#/parameters/pathPatientName'
        - $ref: '#/parameters/bodyDoctor'
      responses:
        '201':
          description: Successful request
          schema:
            $ref: '#/definitions/Patient'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
        default:
          $ref: '#/responses/GeneralError'
  /swagger:
    x-swagger-pipe: swagger_raw
parameters:
  bodyDoctor:
    name: doctor
    in: body
    description: The doctor to be manipulated
    schema:
      $ref: '#/definitions/Doctor'
    required: true
  pathPatientName:
    name: patientName
    in: path
    description: The name of the patient
    type: string
    required: true
  queryRequester:
    name: requester
    in: query
    description: Who requested the patient history
    type: string
responses:
  Forbidden:
    description: Forbidden
    schema:
      $ref: '#/definitions/ErrorResponse'
  GeneralError:
    description: Error
    schema:
      $ref: '#/definitions/ErrorResponse'
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/ErrorResponse'
definitions:
  Doctor:
    required: [name]
    properties:
      name:
        type: string
  Disease:
    required: [name]
    properties:
      name:
        type: string
      ageAtContracted:
        type: integer
  Patient:
    required: [id]
    properties:
      id:
        type: string
      gender:
        type: string
      alive:
        type: boolean
      ageAtDeath:
        type: integer
      disesases:
        type: array
        items:
          $ref: '#/definitions/Disease'
      doctors:
        type: array
        items:
          $ref: '#/definitions/Doctor'
      father:
        $ref: '#/definitions/Patient'
      mother:
        $ref: '#/definitions/Patient'
      children:
        type: array
        items:
          $ref: '#/definitions/Patient'
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
